### ISSUE TITLE
Zscaler account permissions?

### ISSUE THREAD

**Issue by CyberHygiene101** [CrowdStrike/zscaler-FalconX-integration#10]
Which role/permissions are required for the Zscaler account in order for the integration to work?

**Comment by shawndwells** [comment]
Paging @jlangdev , the lead dev

**Comment by jlangdev** [comment]
@CyberHygiene101  

For making any API calls to ZIA, 3 pieces are needed - ZIA admin username/that user’s password/zia API key
There is a single API key at ZIA tenant wide level. There can be multiple different admin users and those admin users can have different RBAC roles. As long as that admin user is able to add URLs to the custom URL category, they should be good to go. 

You can confirm this by just logging into the UI using your admin account and see if you can add URLs to the custom category that this integration uses. If you can, then you should be good to go with running the script and using the integration

**Comment by CyberHygiene101** [comment]
@jlangdev Awesome, thanks for the clarification. Something else we noticed with the Zscaler creds, when a completely invalid zs_password & zs_apiKey are specified in config.py, the output still displays a successful Zscaler authentication.

CrowdStrike/Zscaler Integration initializing...
CTRL-C to exit gracefully
CrowdStrike/Zscaler Integration starting...
CrowdStrike Authentication: Refreshing token.
CrowdStrike Authentication: Successfully authenticated.
Zscaler Authentication: Refreshing token.
Zscaler Authentication: Successfully authenticated.
Traceback (most recent call last):
  File "FolderPath\zscaler-FalconX-integration\main.py", line 49, in <module>
    main()
  File "FolderPath\zscaler-FalconX-integration\main.py", line 18, in main
    i = Integration()  # init integration
  File "FolderPath\zscaler-FalconX-integration\app\integration.py", line 18, in __init__
    self.authenticate()
  File "FolderPath\zscaler-FalconX-integration\app\integration.py", line 45, in authenticate
    self.zs_cat_id = self.zs_cat.custom_category_check()
  File "FolderPath\zscaler-FalconX-integration\app\zscaler\api\category.py", line 39, in custom_category_check
    custom_cats = custom_url_cat.json()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
