### ISSUE TITLE
Integration Error

### ISSUE THREAD

**Issue by gurtej298** [CrowdStrike/zscaler-FalconX-integration#17]
When executing script we are getting following error message. is there any changes required in code?

> Cache-Control: no-store
> x-zscaler-mode: read-write
> Content-Disposition: attachment; filename="api.json"
> Content-Type: application/json
> Content-Length: 66
> Date: Fri, 10 Mar 2023 18:45:13 GMT
> Connection: close
> Server: Zscaler
>
{"code":"AUTHENTICATION_FAILED","message":"AUTHENTICATION_FAILED"}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gpbsing\Desktop\ZS-CS\ZSCS_integration\zscaler-FalconX-integration\intelbridge\__main__.py", line 26, in <module>
    main()
  File "C:\Users\gpbsing\Desktop\ZS-CS\ZSCS_integration\zscaler-FalconX-integration\intelbridge\__main__.py", line 18, in main
    intelbridge.start()
  File "C:\Users\gpbsing\Desktop\ZS-CS\ZSCS_integration\zscaler-FalconX-integration\intelbridge\intelbridge.py", line 114, in start
    zs_token = zs_auth()
               ^^^^^^^^^
  File "C:\Users\gpbsing\Desktop\ZS-CS\ZSCS_integration\zscaler-FalconX-integration\intelbridge\auth\auth.py", line 77, in zs_auth
    response.raise_for_status()
  File "C:\Users\gpbsing\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://zsapi.zscalertwo.net/api/v1/authenticatedSession

**Comment by gurtej298** [comment]
Any update on this issue

**Comment by jlangdev** [comment]
@gurtej298 Hey, looks like an issue with your zscaler API client. Can you confirm that you've filled all the auth configuration correctly in config.ini? Your zscaler client also needs to have the right scopes for pushing to URL categories.
