### ISSUE TITLE
Error When Running Script

### ISSUE THREAD

**Issue by tonyweiss67** [CrowdStrike/zscaler-FalconX-integration#20]
I am getting the following errors when trying to run the integration:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "intelbridge/__main__.py", line 26, in <module>
    main()
  File "intelbridge/__main__.py", line 15, in main
    start_log()
  File "intelbridge/util/util.py", line 19, in start_log
    logging.FileHandler(file),
  File "/usr/lib64/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/zscaler-FalconX-integration/logs/2023-04-14-16_28_55_intel_bridge_log.log'

I have run the install for the requirements.txt

Thanks in advance,

Tony
tony.weiss@hpe.com

**Comment by shotaro88** [comment]
Hi Tony,

I had the same error.  I resolved the error after creating the logs folder manually under zscaler-FalconX-integration.  I'm not sure why the logs folder doesn't exist, but I hope it helps.

Shotaro

**Comment by jlangdev** [comment]
@shotaro88 @tonyweiss67 Hey all, the /logs directory was missing from a recent patch - sorry 'bout that 😎 Most recent patches fix this issue.
