### ISSUE TITLE
Configparserer.py then KeyError 

### ISSUE THREAD

**Issue by piExpr** [CrowdStrike/zscaler-FalconX-integration#26]
x:~$ python3 /home/ubuntu/zscaler-FalconX-integration/intelbridge/intelbridge.py
Traceback (most recent call last):
  File "/home/ubuntu/zscaler-FalconX-integration/intelbridge/intelbridge.py", line 25, in <module>
    from indicators.indicators import get_indicators, prepare_indicators #, write_data
  File "/home/ubuntu/zscaler-FalconX-integration/intelbridge/indicators/indicators.py", line 10, in <module>
    from auth.auth import cs_auth
  File "/home/ubuntu/zscaler-FalconX-integration/intelbridge/auth/auth.py", line 16, in <module>
    cs_config = config['CROWDSTRIKE']
  File "/usr/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'CROWDSTRIKE'

**Comment by marcispauls** [comment]
from the error seems you dont have config.ini with [CROWDSTRIKE]

**Comment by piExpr** [comment]
Using the config.ini with all the required API creds. Using VSCode on my machine with all the dependencies installed. Should the intelbridge.py be on env variable path? Is there anything else needed as far as making edits to the code? Getting no where with this. tia

**Comment by marcispauls** [comment]
not really - did as described, created config and done

**Comment by piExpr** [comment]
What was your env setup like? Local machine with some compiler? Docket container? Some flavor linux?

I'm running on my mac with VScode the folder path to repo

**Comment by piExpr** [comment]
used the original repo with config.py then ran setup... appears to be working

recent repo kept returning config parser and all sorts of error
