### ISSUE TITLE
get_all_indicators error

### ISSUE THREAD

**Issue by ssteenhoek** [CrowdStrike/zscaler-FalconX-integration#31]
Has anyone seen this error or know what is needed to resolve?

11/07/2023 10:29:11 AM Log utility started. Writing to ./logs/2023-11-07-16_29_11_intel_bridge_log.log
11/07/2023 10:29:11 AM Intel Bridge main routine starting...
11/07/2023 10:29:11 AM Initializing Intel Bridge
11/07/2023 10:29:11 AM Authenticating client <redacted key> to Falcon API
11/07/2023 10:29:11 AM Authenticating user <redacted account> to Zscaler API
11/07/2023 10:29:13 AM Starting Pull/Prepare/Push Loop # 1 With new indicators
11/07/2023 10:29:13 AM Confirming URL category CrowdStrike exists
11/07/2023 10:29:14 AM Validated URL category CrowdStrike
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\zscaler-FalconX-integration\intelbridge\__main__.py", line 26, in <module>
    main()
  File "C:\zscaler-FalconX-integration\intelbridge\__main__.py", line 18, in main
    intelbridge.start()
  File "C:\zscaler-FalconX-integration\intelbridge\intelbridge.py", line 135, in start
    deleted, loop = self.etl_loop(falcon, zs_token, deleted, loop)
  File "C:\intelbridge\intelbridge.py", line 104, in etl_loop
    indicators = self.pull(falcon, deleted)
  File "C:\zscaler-FalconX-integration\intelbridge\intelbridge.py", line 50, in pull
    indicators = get_indicators(falcon, deleted)
  File "C:\zscaler-FalconX-integration\intelbridge\indicators\indicators.py", line 55, in get_indicators
    return get_all_indicators(falcon)
  File "C:\zscaler-FalconX-integration\intelbridge\indicators\indicators.py", line 155, in get_all_indicators
    ecode = err["code"]
KeyError: 'code'

**Comment by ssteenhoek** [comment]
Fix was to add the new Crowdstrike API key permissions and base URL, per instructions.
