### ISSUE TITLE
Script is running into errors

### ISSUE THREAD

**Issue by rohan-zscaler** [CrowdStrike/zscaler-FalconX-integration#32]
12/19/2023 05:10:30 PM Successfully prepared 997 Indicators for Zscaler API
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\__main__.py", line 26, in <module>
    main()
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\__main__.py", line 18, in main
    intelbridge.start()
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\intelbridge.py", line 135, in start
    deleted, loop = self.etl_loop(falcon, zs_token, deleted, loop)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\intelbridge.py", line 105, in etl_loop
    ingestable, amount_rejected = self.prepare(zs_token, indicators)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\intelbridge.py", line 59, in prepare
    prepared, amount_rejected_crwd = prepare_indicators(indicators)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\indicators\indicators.py", line 105, in prepare_indicators
    write_rejected("regex filter rejected", rejected)
  File "C:\Users\eparra\Desktop\zscaler-FalconX-integration\intelbridge\util\util.py", line 100, in write_rejected
    f = open(data_file, 'a')
        ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'logs/rejected_log/data_rejected_2023-12-19.log'

I had to comment following lines to make it work. Can you pls take a look at add the fix?

 def write_rejected(message, entry):
 95     """writes rejected URLs to a log file
 96     """
 97 #    rejected_indicators_data = f"logs/rejected_log/data_rejected"
 98 #   data_file = rejected_indicators_data
 99 #  data_file = data_file + "_" + time.strftime("%Y-%m-%d", time.gmtime()) +".log"
100 #    f = open(data_file, 'a')
101   #  f.write(f"{time.strftime('%Y-%m-%d', time.gmtime())}: {message}: {entry}")
102    # f.close()
103     return

**Comment by jrandrusk** [comment]
This is a bug in that it's attempting to write to a non-existent directory. Quick fix is just to do a` mkdir rejected_log `under the logs directory and re-run the script. Would have thought this would have been fixed by now.

**Comment by rohan-zscaler** [comment]
Can you please update the script to include this and push it to Github ?

Thanks, 

Rohan

**Comment by yaroslav-nakonechnikov** [comment]
@rohan-zscaler please review https://github.com/CrowdStrike/zscaler-FalconX-integration/pull/27/
