### ISSUE TITLE
Getting py errors, please help

### ISSUE THREAD

**Issue by ericeacosta** [CrowdStrike/zscaler-FalconX-integration#33]
c:\zscaler-FalconX-integration-main>python intelbridge
02/21/2024 03:41:26 PM Log utility started. Writing to ./logs/2024-02-21-20_41_26_intel_bridge_log.log
02/21/2024 03:41:26 PM Intel Bridge main routine starting...
02/21/2024 03:41:26 PM Initializing Intel Bridge
02/21/2024 03:41:26 PM Authenticating client xxxxxxxxxxxxxxxxxxxxxxxxxxxx to Falcon API
02/21/2024 03:41:26 PM Authenticating user crowdstrike@xxxxxx.com to Zscaler API
02/21/2024 03:41:27 PM Starting Pull/Prepare/Push Loop # 1 With new indicators
02/21/2024 03:41:27 PM Confirming URL category CrowdStrike exists
02/21/2024 03:41:28 PM Validated URL category CrowdStrike
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\zscaler-FalconX-integration-main\intelbridge\__main__.py", line 26, in <module>
    main()
  File "c:\zscaler-FalconX-integration-main\intelbridge\__main__.py", line 18, in main
    intelbridge.start()
  File "c:\zscaler-FalconX-integration-main\intelbridge\intelbridge.py", line 135, in start
    deleted, loop = self.etl_loop(falcon, zs_token, deleted, loop)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\zscaler-FalconX-integration-main\intelbridge\intelbridge.py", line 104, in etl_loop
    indicators = self.pull(falcon, deleted)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\zscaler-FalconX-integration-main\intelbridge\intelbridge.py", line 50, in pull
    indicators = get_indicators(falcon, deleted)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\zscaler-FalconX-integration-main\intelbridge\indicators\indicators.py", line 56, in get_indicators
    return get_all_indicators(falcon)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\zscaler-FalconX-integration-main\intelbridge\indicators\indicators.py", line 158, in get_all_indicators
    ecode = err["code"]
            ~~~^^^^^^^^
KeyError: 'code'

c:\zscaler-FalconX-integration-main>

**Comment by ericeacosta** [comment]
Error in API Secret (Noob point)
