### ISSUE TITLE
Main.py run issue

### ISSUE THREAD

**Issue by mimirivo** [CrowdStrike/zscaler-FalconX-integration#9]
I made config.py configuration and when i run main.py i got the below error

Traceback (most recent call last):
  File "C:\Users\abdelmageed.ahmed\zscaler-FalconX-integration\main.py", line 3, in <module>
    from app.integration import Integration
  File "C:\Users\abdelmageed.ahmed\zscaler-FalconX-integration\app\integration.py", line 2, in <module>
    from app.crowdstrike.crowdstrike_auth import CrowdStrikeAuth
  File "C:\Users\abdelmageed.ahmed\zscaler-FalconX-integration\app\crowdstrike\crowdstrike_auth.py", line 2, in <module>
    from requests.exceptions import HTTPError
ModuleNotFoundError: No module named 'requests'

**Comment by CyberHygiene101** [comment]
If you run this, it will do the trick: python -m pip install requests

**Comment by shawndwells** [comment]
@jlangdev is this something that should be added into a "prerequisites" or similar section?

**Comment by shawndwells** [comment]
dependencies.... prerequisites.... something to that effect

**Comment by jlangdev** [comment]
@shawndwells 
Good point - it has been done

**Comment by mimirivo** [comment]
thanks CyberHygiene101 .. python -m pip install requests worked great and integration done ty all
